"""initial schema

Revision ID: 8b8bcc89bc22
Revises: 
Create Date: 2026-06-10 12:15:55.701105

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8b8bcc89bc22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_flow_id'), ['flow_id'], unique=False)

    op.create_table('runs',
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_session_id'), ['session_id'], unique=False)

    op.create_table('stamps',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id', 'step')
    )
    op.create_table('nodes',
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open_args_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('node_uuid')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_run_id'), ['run_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('eval_id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['node_uuid'], ['nodes.node_uuid'], ),
    sa.PrimaryKeyConstraint('eval_id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_evaluator'), ['evaluator'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_node_uuid'), ['node_uuid'], unique=False)

    op.create_table('guardrails',
    sa.Column('guardrail_id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('stamp_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['node_uuid'], ['nodes.node_uuid'], ),
    sa.PrimaryKeyConstraint('guardrail_id')
    )
    with op.batch_alter_table('guardrails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardrails_node_uuid'), ['node_uuid'], unique=False)

    op.create_table('llm_calls',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_index', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('system_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['node_uuid'], ['nodes.node_uuid'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_node_uuid'), ['node_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_llm_calls_session_model', ['session_id', 'model_name'], unique=False)

    op.create_table('memory',
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('stamp_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['node_uuid'], ['nodes.node_uuid'], ),
    sa.PrimaryKeyConstraint('memory_id')
    )
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_node_uuid'), ['node_uuid'], unique=False)

    op.create_table('middleware_traces',
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middleware_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('stamp_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['node_uuid'], ['nodes.node_uuid'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('middleware_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_middleware_traces_node_uuid'), ['node_uuid'], unique=False)

    op.create_table('node_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stamp_step', sa.Integer(), nullable=False),
    sa.Column('stamp_time', sa.Float(), nullable=False),
    sa.Column('stamp_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['node_uuid'], ['nodes.node_uuid'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    with op.batch_alter_table('node_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_versions_node_uuid'), ['node_uuid'], unique=False)

    op.create_table('requests',
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sink_node_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_args_json', sa.JSON(), nullable=True),
    sa.Column('input_kwargs_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('output_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_stamp_step', sa.Integer(), nullable=False),
    sa.Column('created_stamp_time', sa.Float(), nullable=False),
    sa.Column('stamp_step', sa.Integer(), nullable=False),
    sa.Column('stamp_time', sa.Float(), nullable=False),
    sa.Column('parent_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_request_id'], ['requests.request_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.ForeignKeyConstraint(['sink_node_uuid'], ['nodes.node_uuid'], ),
    sa.ForeignKeyConstraint(['source_node_uuid'], ['nodes.node_uuid'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_sink_node_uuid'), ['sink_node_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_source_node_uuid'), ['source_node_uuid'], unique=False)

    op.create_table('failures',
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exception_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['llm_calls.call_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_call_id'), ['call_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_name'), ['name'], unique=False)

    op.create_table('tool_responses',
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.tool_call_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_responses')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_name'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_message_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_call_id'))

    op.drop_table('messages')
    op.drop_table('failures')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_source_node_uuid'))
        batch_op.drop_index(batch_op.f('ix_requests_sink_node_uuid'))
        batch_op.drop_index(batch_op.f('ix_requests_run_id'))

    op.drop_table('requests')
    with op.batch_alter_table('node_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_versions_node_uuid'))

    op.drop_table('node_versions')
    with op.batch_alter_table('middleware_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_middleware_traces_node_uuid'))

    op.drop_table('middleware_traces')
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_node_uuid'))

    op.drop_table('memory')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_calls_session_model')
        batch_op.drop_index(batch_op.f('ix_llm_calls_session_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_node_uuid'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('guardrails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardrails_node_uuid'))

    op.drop_table('guardrails')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_node_uuid'))
        batch_op.drop_index(batch_op.f('ix_evaluations_evaluator'))

    op.drop_table('evaluations')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_run_id'))

    op.drop_table('nodes')
    op.drop_table('stamps')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_session_id'))

    op.drop_table('runs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_flow_id'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
