site_name: Request Completion Docs
site_url: https://something
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.prefetch
    - search.suggest
    - content.code.copy
    - content.code.highlight

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - js/mermaid-config.js

extra_css:
  - css/extra.css

nav:
  - Home: index.md


  - Guides:
        - guides/index.md
        - guides/agents.md

  - Tutorials:
        - tutorials/index.md




  - Tools + MCP:
      - tools_mcp/index.md
      - Create Your Own Tool: tools_mcp/create_your_own.md
      - MCP:
          - tools_mcp/mcp/index.md
          - Using MCP: tools_mcp/mcp/MCP_tools_in_RT.md
          - Creating an MCP: tools_mcp/mcp/RTtoMCP.md

      - Integrations:
        - Notion: tools_mcp/guides/notion.md
        - Github: tools_mcp/guides/github.md
        - Python Sandbox: tools_mcp/guides/python_sandbox.md
        - Shell Bash: tools_mcp/guides/shell_bash.md
        - Slack: tools_mcp/guides/slack.md
        - Web Search: tools_mcp/guides/websearch_integration.md

  - Observability:
        - observability/index.md

  - LLM Support:
      - llm_support/index.md

  - Deployments:
        - deployments/index.md

  - Advanced Usage:
        - advanced_usage/index.md

  - Samples:
      - samples/index.md

  - System Internals:
        - system_internals/index.md

  - API Reference:
      - api_reference/index.md
  
  - System Overview:
      - system_internals/index.md
      - Coordinator: system_internals/Coordinator.md
      - Runner: system_internals/Runner.md
      - PubSub: system_internals/PubSub.md


plugins:
  - search
  - mkdocstrings
#  - mkdocs-mermaid2-plugin
#  - awesome-pages

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg



