site_name: RailTracks Docs
site_url: https://something

repo_name: railtracks
repo_url: https://github.com/RailtownAI/railtracks

theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.prefetch
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - content.code.highlight
    - content.code.annotate

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span

extra_css:
  - css/extra.css

extra:
  generator: false

nav:
  - Home: index.md

  - Quickstart: quickstart/quickstart.md
  
  - Tutorials:
      - Background:
          - Agents: tutorials/guides/agents.md
          - Tools: tutorials/guides/tools.md
          - Async/Await: tutorials/guides/async_await.md
      - Building your first agent: tutorials/byfa.md
      - Running your first agent: tutorials/ryfa.md

  - Tools + MCP:
      - Equip your LLMs: tools_mcp/tools_mcp.md
      - MCP:
          - Model Context Protocol: tools_mcp/mcp/mcp.md
          - Using MCP: tools_mcp/mcp/MCP_tools_in_RT.md
          - Creating an MCP: tools_mcp/mcp/RTtoMCP.md

      - Tools:
          - What is a Tool: tools_mcp/tools/tools.md
          - Functions as Tools: tools_mcp/tools/functions_as_tools.md
          - Agents as Tools: tools_mcp/tools/agents_as_tools.md
          - Advanced Tooling: tools_mcp/tools/advanced_usage.md

      - Integrations:
          - Notion: tools_mcp/guides/notion.md
          - Github: tools_mcp/guides/github.md
          - Python Sandbox: tools_mcp/guides/python_sandbox.md
          - Shell Bash: tools_mcp/guides/shell_bash.md
          - Slack: tools_mcp/guides/slack.md
          - Web Search: tools_mcp/guides/websearch_integration.md

  - Observability:
      - Visualization: observability/visualization.md
      - Logging: observability/logging.md
      - Broadcasting: observability/broadcasting.md
      - Local Chat: observability/chat.md
      - Error Handling: observability/error_handling.md

  - LLM Support:
      - Supported Providers: llm_support/providers.md
      - Prompts and Context Injection: llm_support/prompts.md
      - Configuration: llm_support/config.md

  - Deployments:
      - Docker: deployments/docker.md

  - Advanced Usage:
      - Session: advanced_usage/session.md
      - Context: advanced_usage/context.md
      - Custom Nodes: advanced_usage/node_builder.md

  - Samples:
      - samples/index.md

  - System Internals:
      - Overview: system_internals/overview.md
      - Core Concepts: system_internals/concepts.md
      - Node Abstraction: system_internals/node.md
      - Session Management: system_internals/session.md
      - PubSub Messaging: system_internals/pubsub.md
      - Coordinator Orchestration: system_internals/coordinator.md

  - API Reference:
      - Generated: api_reference/generated/railtracks.html


