site_name: RailTracks Docs
site_url: https://something
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.prefetch
    - search.suggest
    - content.code.copy
    - content.code.highlight
  code:
    highlight_theme:
      light: github
      dark: dracula





extra_css:
  - css/extra.css

nav:
  - Home: index.md




  - Tutorials:
        - tutorials/byfa.md
        - Background:
            - tutorials/guides/index.md
            - Agents: tutorials/guides/agents.md
            - Tools: tutorials/guides/tools.md

  - Tools + MCP:
      - tools_mcp/index.md
      - Create Your Own Tool: tools_mcp/create_your_own.md
      - MCP:
          - tools_mcp/mcp/index.md
          - Using MCP: tools_mcp/mcp/MCP_tools_in_RT.md
          - Creating an MCP: tools_mcp/mcp/RTtoMCP.md

      - Integrations:
        - Notion: tools_mcp/guides/notion.md
        - Github: tools_mcp/guides/github.md
        - Python Sandbox: tools_mcp/guides/python_sandbox.md
        - Shell Bash: tools_mcp/guides/shell_bash.md
        - Slack: tools_mcp/guides/slack.md
        - Web Search: tools_mcp/guides/websearch_integration.md

  - Observability:
        - observability/index.md
        - Visualization: observability/visualization.md
        - Logging: observability/logging.md
        - Streaming: observability/streaming.md

  - LLM Support:
      - llm_support/index.md
      - Prompts and Context Injection: llm_support/prompts.md

  - Deployments:
        - deployments/index.md

  - Advanced Usage:
        - advanced_usage/index.md
        - Context: advanced_usage/context.md
        - Prompt Injection: advanced_usage/prompt_injection.md

  - Samples:
      - samples/index.md

  - System Internals:
        - system_internals/index.md
        - Coordinator: system_internals/Coordinator.md

  - API Reference:
      - api_reference/index.md
  
  - System Overviews:
      - system_internals/index.md
      - Node: system_internals/node.md
      - Runner: system_internals/runner.md
      - PubSub: system_internals/pubsub.md
      - Coordinator: system_internals/coordinator.md


plugins:
  - search
  - mermaid2



markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list


