[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"


[project]
name = "requestcompletion"
authors = [
    { name = "Logan Underwood", email = "logan@railtown.ai" },
    { name = "Levi Varsanyi", email = "levi@railtownn.ai" },
    { name = "Jaime Bueza", email = "jaime@railtown.ai" },
]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "colorama >= 0.4.6",
    "llama-index >= 0.12.0, <= 0.12.11",
    "llama-index-core <= 0.12.38",
    "llama-index-llms-anthropic >= 0.6.0",
    "llama-index-llms-openai >= 0.3.0,<=0.3.38",
    "mcp >= 1.9.0",
    "nltk >= 3.9.1",
    "openai <= 1.81.0",
    "pydantic >= 2.5.3,<3",
    "python-dotenv >= 1.0.0",
    "pyvis >= 0.3.1",
    "requests >=2.31,<3",
    "requests-mock >= 1.12.1",
]

[project.urls]
Home = "https://railtown.ai"


[tool.flit.module]
name = "requestcompletion"

[tool.black]
line-length = 120
fast = true

[project.optional-dependencies]
test = ["pytest >=7.1.2"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
asyncio_mode = "auto"
