name: 🐛 Bug Report
description: Report a bug or issue with railtracks.
title: "[Bug] "
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what you expected to happen and what actually happened.
      placeholder: |
        I expected the form to submit successfully, but it throws a 500 error.
    validations:
      required: true

  - type: textarea
    id: reproducing_steps
    attributes:
      label: Reproducing Steps (include code examples if applicable)
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Navigate to the form page
        2. Fill in the required fields
        3. Submit the form
        4. See the error
        
        ```python
        # Example code that reproduces the issue
        submit_form(data)
        ```
      render: markdown
    validations:
      required: true

  - type: textarea
    id: stack_trace
    attributes:
      label: Relevant Stack Trace (optional)
      description: Paste any error messages or stack traces here.
      placeholder: |
        ```
        Traceback (most recent call last):
        ...
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information, such as screenshots, related issues, or environment notes.
      placeholder: This happens only on macOS with Python 3.10.
    validations:
      required: false

  - type: input
    id: operating_system
    attributes:
      label: Operating System
      placeholder: e.g. Windows 11, macOS 14, Ubuntu 22.04

  - type: input
    id: railtracks_version
    attributes:
      label: railtracks Version
      placeholder: e.g. 0.1.0

  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: e.g. 3.10.8
