blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/RailtownAI/railtracks/tree/main/docs
    about: Check the documentation for guides and API reference
  - name: 💬 Discussions
    url: https://github.com/RailtownAI/railtracks/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/RailtownAI/railtracks/security/advisories/new
    about: Report security vulnerabilities privately