name: ✨ Feature Request
description: Suggest a new feature or enhancement for railtracks.
title: "[Feature] "
labels: [feature]

body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Request
      description: Describe the feature you'd like to see added. Optionally include any solution ideas or implementation suggestions you may have.
      placeholder: |
        A clear and concise description of the new feature you'd like to see.
        
        Optional: If you have ideas on how this could be implemented, feel free to include them here. For example:
        - Relevant code examples
        - Design ideas
        - API suggestions
        - Implementation approaches
    validations:
      required: true


  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context that will help us understand the feature request.
      placeholder: Related issues, libraries, or notes.
    validations:
      required: false
