name: "[Maintainer Only] Feature"
description: "A contained set of user-facing requirements. Railtracks maintainers/team members only."
labels: ["[Maintainer] feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What will the user be able to do once this is done? Include design/pre-work if relevant. Include a bulleted list of specific requirements.
    validations:
      required: true
