name: ✨ Feature Request
description: Suggest a new feature or enhancement for railtracks.
title: "[Feature] "
labels: [feature]

body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added.
      placeholder: A clear and concise description of the new feature.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? Include any ideas.
      placeholder: Describe the implementation or design you'd suggest.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or related links.
      placeholder: Related issues, libraries, or notes.
    validations:
      required: false
