name: "Task"
description: "A well-scoped, unambiguous piece of work. Typically created by team members."
labels: ["[Maintainer] task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the change, in code terms? Include specific requirements as a bulleted list.
    validations:
      required: true
