name: 🧹 Tech Debt
description: Outline technical debt in the code base
title: "[Tech Debt] "
labels: [tech debt]

body:
  - type: textarea
    id: description_solution
    attributes:
      label: Description (and/or) Solution
      description: Describe the technical debt and/or how you suggest resolving it.
      placeholder: |
        The current implementation is hard to test due to tightly coupled logic.
        Suggest extracting the logic into a separate service class.
    validations:
      required: true

  - type: textarea
    id: context_references
    attributes:
      label: Additional Context
      description: Any other context that will help us understand the technical debt.
      placeholder: e.g. Related to issue #42 or PR #103
    validations:
      required: false
