name: Run E2E Tests (Manual)

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  end_to_end_tests:
    name: End to End Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Run E2E tests
        env:
          OPENAI_API_KEY: ${{ secrets.E2E_TESTS_OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.E2E_TESTS_ANTHROPIC_API_KEY }}
          HF_TOKEN: ${{ secrets.E2E_TESTS_HUGGINGFACE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.E2E_TESTS_GEMINI_API_KEY }}
          COHERE_API_KEY: ${{ secrets.E2E_TESTS_COHERE_API_KEY }}

        run: |
          pytest -s -v --junit-xml=end-to-end-test-results.xml  packages/railtracks/tests/end_to_end packages/railtracks/tests/llm_live_tests
