name: Push to Main Tests

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  ruff-lint:
    name: Check Code Formatting and Linting with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}" # Specify the Python version you are using

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Lint Check
        run: ruff check . --no-fix

      - name: Run Ruff Format Check
        run: ruff format --check .

  check-licenses:
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Run License Check
        run: |
          chmod +x scripts/check_licenses.sh
          ./scripts/check_licenses.sh

      - name: License Check Analysis
        if: always()
        run: |
          if [ -f core-licenses-summary.md ]; then
            cat core-licenses-summary.md >> $GITHUB_STEP_SUMMARY
            echo "### 📦 Licenses Found" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat core-licenses.md >> $GITHUB_STEP_SUMMARY
          fi

  documentation_validation:
    name: Documentation Validation
    runs-on: ubuntu-latest
    needs:
      - ruff-lint
      - check-licenses

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Validate documentation
        run: |
          ./scripts/docs_validation.sh

  pyproject_dependency_order:
    name: Validate pyproject.toml Dependency Order
    runs-on: ubuntu-latest
    needs:
      - ruff-lint
      - check-licenses

    steps:
      - name: Print System Architecture
        run: uname -m

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Check pyproject.toml dependency order
        run: |
          python scripts/check_dependencies_sorted.py

  tests:
    name: Tests
    runs-on: windows-latest
    needs:
      - ruff-lint
      - check-licenses
      - documentation_validation
      - pyproject_dependency_order

    steps:
      - name: Print System Architecture
        run: uname -m

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Run tests
        shell: bash
        run: |
          pytest -s -v --junit-xml=unit-test-results.xml packages/railtracks/tests/unit_tests/ packages/railtracks/tests/integration_tests/

  build-railtracks-cli:
    name: Test Railtracks CLI
    runs-on: ubuntu-latest
    needs:
      - ruff-lint
      - check-licenses

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install CLI dependencies
        working-directory: packages/railtracks-cli
        run: |
          python -m pip install --upgrade pip
          pip install -e ../railtracks
          pip install -e .

      - name: Run tests
        shell: bash
        working-directory: packages/railtracks-cli
        continue-on-error: true
        run: |
          python run_tests.py

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cli-test-results
          path: packages/railtracks-cli/test-results.xml
          if-no-files-found: ignore
